import AppKit
import Combine
import CryptoKit
import ImageIO

/// The last few things copied, newest first. Kept in memory only, so the history is gone
/// when Cranny quits.
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    struct Representation {
        let type: NSPasteboard.PasteboardType
        let data: Data
    }

    struct Item: Identifiable {
        enum Kind {
            case text(String)
            case link(URL)
            case image(NSImage)
            case files([URL])
        }

        let id: UUID
        let kind: Kind
        /// Everything that was on the clipboard, one list per pasteboard item in the order the
        /// app offered it, so copying it back keeps the formatting.
        let contents: [[Representation]]
        /// Two copies with the same signature are the same thing.
        let signature: String
        let appName: String?
        let appIcon: NSImage?
    }

    /// Whether macOS lets Cranny read the clipboard.
    enum Access { case allowed, needsPermission, blocked }

    @Published private(set) var items: [Item] = []
    @Published private(set) var access: Access = .allowed
    /// The item that's on the clipboard right now, if it's in the history.
    @Published private(set) var currentID: UUID?
    /// The item that was just copied back, for a moment of feedback.
    @Published private(set) var justCopiedID: UUID?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount = 0
    private var timer: Timer?
    private var bag = Set<AnyCancellable>()
    private var copiedWork: DispatchWorkItem?

    /// Marks for private or temporary data, used by password managers and others (nspasteboard.org).
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "Pasteboard generator type",
    ]
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png, .tiff, .init("public.jpeg"), .init("public.heic"), .init("com.compuserve.gif"),
    ]
    private static let maxRepresentation = 10 * 1024 * 1024
    private static let maxItem = 16 * 1024 * 1024

    private init() {}

    func start() {
        lastChangeCount = pasteboard.changeCount
        refreshAccess()
        // Start with what's already on the clipboard, but never ask for permission at launch.
        if AppSettings.shared.clipboardHistory, permission == .allow { capture() }

        let timer = Timer(timeInterval: 0.5, repeats: true) { _ in
            MainActor.assumeIsolated { ClipboardStore.shared.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        AppSettings.shared.$clipboardHistory
            .dropFirst()
            .sink { [weak self] on in if !on { self?.removeAll() } }
            .store(in: &bag)
        AppSettings.shared.$clipboardSize
            .dropFirst()
            .sink { [weak self] size in self?.trim(to: size) }
            .store(in: &bag)
    }

    // MARK: Watching for copies

    private enum Permission { case allow, notAsked, ask, deny }

    /// macOS's clipboard permission for Cranny. Before macOS 15.4 there's no such thing, and
    /// when macOS doesn't enforce it, it reports "allow".
    private var permission: Permission {
        // For checking the permission card: `defaults write io.github.rdbms234.Cranny debugClipboardAccess ask` (or deny).
        switch UserDefaults.standard.string(forKey: "debugClipboardAccess") {
        case "ask": return .ask
        case "deny": return .deny
        default: break
        }
        if #available(macOS 15.4, *) {
            switch pasteboard.accessBehavior {
            case .alwaysAllow: return .allow
            case .alwaysDeny: return .deny
            case .ask: return .ask
            default: return .notAsked
            }
        }
        return .allow
    }

    private func refreshAccess() {
        let next: Access
        switch permission {
        case .allow, .notAsked: next = .allowed
        case .ask: next = .needsPermission
        case .deny: next = .blocked
        }
        if access != next { access = next }
    }

    /// The clipboard's change count is cheap to read and never asks for permission, so it's
    /// checked twice a second and the clipboard itself is only read after something changed.
    private func poll() {
        if access != .allowed {
            // Cranny may have just been allowed in System Settings.
            refreshAccess()
            if access == .allowed, AppSettings.shared.clipboardHistory {
                lastChangeCount = pasteboard.changeCount
                capture()
            }
        }
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard AppSettings.shared.clipboardHistory else { return }
        refreshAccess()
        guard access == .allowed else {
            currentID = nil
            return
        }
        capture()
        // If macOS enforces clipboard privacy, that read was its one prompt, which also lists
        // Cranny in Privacy & Security. From then on Cranny waits to be allowed there.
        refreshAccess()
    }

    private func capture() {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else {
            currentID = nil
            return
        }
        let types = Set(pasteboardItems.flatMap(\.types).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes), let item = makeItem(from: pasteboardItems) else {
            currentID = nil
            return
        }
        var next = items.filter { $0.signature != item.signature }
        next.insert(item, at: 0)
        items = Array(next.prefix(AppSettings.shared.clipboardSize))
        currentID = item.id
    }

    private func makeItem(from pasteboardItems: [NSPasteboardItem]) -> Item? {
        var contents: [[Representation]] = []
        var total = 0
        for pasteboardItem in pasteboardItems {
            var representations: [Representation] = []
            for type in pasteboardItem.types {
                // File promises point at data that only exists for the original drag or copy.
                if type.rawValue.localizedCaseInsensitiveContains("promise") { continue }
                guard let data = pasteboardItem.data(forType: type), data.count <= Self.maxRepresentation else { continue }
                // Past the size limit, only small things like file links and short text still fit.
                guard total + data.count <= Self.maxItem || data.count < 4096 else { continue }
                total += data.count
                representations.append(Representation(type: type, data: data))
            }
            if !representations.isEmpty { contents.append(representations) }
        }
        guard !contents.isEmpty, let described = Self.describe(contents) else { return nil }
        let signature = described.signature
        let app = NSWorkspace.shared.frontmostApplication
        let source = app?.bundleIdentifier == Bundle.main.bundleIdentifier ? nil : app
        return Item(
            id: items.first { $0.signature == signature }?.id ?? UUID(),
            kind: described.kind, contents: contents, signature: signature,
            appName: source?.localizedName, appIcon: source?.icon
        )
    }

    /// Works out what kind of thing was copied, and its signature.
    private static func describe(_ contents: [[Representation]]) -> (kind: Item.Kind, signature: String)? {
        func data(_ type: NSPasteboard.PasteboardType, in representations: [Representation]) -> Data? {
            representations.first { $0.type == type }?.data
        }

        // Finder puts one pasteboard item on the clipboard per file.
        let files = contents.compactMap { data(.fileURL, in: $0).flatMap { URL(dataRepresentation: $0, relativeTo: nil) } }
        if !files.isEmpty {
            return (.files(files), "files:" + files.map(\.path).joined(separator: "\n"))
        }

        let first = contents[0]
        let text = data(.string, in: first).flatMap { String(data: $0, encoding: .utf8) }
        let hasText = !(text?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
        // A picture, unless the app offered text first (rich text can carry pictures too).
        if let image = first.first(where: { imageTypes.contains($0.type) }),
           !hasText || imageTypes.contains(first[0].type),
           let preview = thumbnail(of: image.data) {
            return (.image(preview), "image:" + hash(image.data))
        }
        if let text, hasText {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed),
               let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https", url.host != nil {
                return (.link(url), "link:" + trimmed)
            }
            return (.text(text), "text:" + hash(Data(text.utf8)))
        }
        if let data = data(.URL, in: first), let url = URL(dataRepresentation: data, relativeTo: nil) {
            return (.link(url), "link:" + url.absoluteString)
        }
        return nil
    }

    private static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// A small copy of a copied picture for its tile, so big screenshots don't sit in memory
    /// at full size while they're shown.
    private static func thumbnail(of data: Data) -> NSImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 400,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        return NSImage(cgImage: image, size: NSSize(width: image.width, height: image.height))
    }

    // MARK: Using the history

    /// Puts an item back on the clipboard, with all its formats, and moves it to the front.
    func copy(_ item: Item) {
        pasteboard.clearContents()
        pasteboard.writeObjects(item.contents.map { representations in
            let pasteboardItem = NSPasteboardItem()
            for representation in representations {
                pasteboardItem.setData(representation.data, forType: representation.type)
            }
            return pasteboardItem
        })
        // Cranny's own copy isn't a new item.
        lastChangeCount = pasteboard.changeCount
        if let index = items.firstIndex(where: { $0.id == item.id }), index > 0 {
            var next = items
            next.insert(next.remove(at: index), at: 0)
            items = next
        }
        currentID = item.id
        justCopiedID = item.id
        copiedWork?.cancel()
        let work = DispatchWorkItem {
            MainActor.assumeIsolated { ClipboardStore.shared.justCopiedID = nil }
        }
        copiedWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.9, execute: work)
    }

    func remove(_ id: UUID) {
        items.removeAll { $0.id == id }
        if currentID == id { currentID = nil }
    }

    func removeAll() {
        items.removeAll()
        currentID = nil
    }

    private func trim(to size: Int) {
        if items.count > size { items = Array(items.prefix(size)) }
        if let currentID, !items.contains(where: { $0.id == currentID }) { self.currentID = nil }
    }

    static func openPrivacySettings() {
        let modern = URL(string: "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension?Privacy_Pasteboard")
        let legacy = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Pasteboard")
        if let modern, NSWorkspace.shared.open(modern) { return }
        if let legacy { NSWorkspace.shared.open(legacy) }
    }
}
